function dh0 = get_dh0(in1,in2,in3,theta_begin,theta_end)
%GET_DH0
%    DH0 = GET_DH0(IN1,IN2,IN3,THETA_BEGIN,THETA_END)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    10-Jan-2017 16:39:23

dq8 = in2(8,:);
dq9 = in2(9,:);
dq10 = in2(10,:);
dq11 = in2(11,:);
dh0 = [dq8.*(1.0./2.0)+dq9.*(1.0./2.0);dq10.*(1.0./2.0)+dq11.*(1.0./2.0);-dq8+dq9;-dq10+dq11];
