function dh0dq = get_dh0dq(in1,in2,in3,theta_begin,theta_end)
%GET_DH0DQ
%    DH0DQ = GET_DH0DQ(IN1,IN2,IN3,THETA_BEGIN,THETA_END)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Jan-2017 20:47:27

dh0dq = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0,0.0,-1.0,0.0,1.0./2.0,0.0,1.0,0.0,0.0,1.0./2.0,0.0,-1.0,0.0,1.0./2.0,0.0,1.0],[4,11]);
