function ds = get_ds(in1,in2,theta_begin,theta_end)
%GET_DS
%    DS = GET_DS(IN1,IN2,THETA_BEGIN,THETA_END)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Jan-2017 15:29:10

dq3 = in2(3,:);
dq4 = in2(4,:);
dq5 = in2(5,:);
ds = -(dq3+dq4.*(1.0./2.0)+dq5.*(1.0./2.0))./(theta_end-theta_begin);
