function s = get_s(in1,in2,theta_begin,theta_end)
%GET_S
%    S = GET_S(IN1,IN2,THETA_BEGIN,THETA_END)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Jan-2017 15:29:10

q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
s = -(q3+q4.*(1.0./2.0)+q5.*(1.0./2.0)+theta_begin)./(theta_end-theta_begin);
